project_name: echo-service
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  -
    id: foo
    rlcp: true
    format: tar.gz
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - ghcr.io/afrouper/{{ .ProjectName }}:{{ .Version }}-amd64
      - docker.io/afrouper/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/afrouper/{{ .ProjectName }}:latest-amd64
      - docker.io/afrouper/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/afrouper/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/afrouper/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - ghcr.io/afrouper/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/afrouper/{{ .ProjectName }}:latest-arm64
      - docker.io/afrouper/{{ .ProjectName }}:{{ .Version }}-arm64
      - docker.io/afrouper/{{ .ProjectName }}:latest-arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.url=https://github.com/afrouper/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/afrouper/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.licenses=Apache-2.0"

docker_manifests:
  - name_template: ghcr.io/afrouper/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/afrouper/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/afrouper/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/afrouper/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/afrouper/{{ .ProjectName }}:latest-amd64
      - ghcr.io/afrouper/{{ .ProjectName }}:latest-arm64

  - name_template: docker.io/afrouper/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - docker.io/afrouper/{{ .ProjectName }}:{{ .Version }}-amd64
      - docker.io/afrouper/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: docker.io/afrouper/{{ .ProjectName }}:latest
    image_templates:
      - docker.io/afrouper/{{ .ProjectName }}:latest-amd64
      - docker.io/afrouper/{{ .ProjectName }}:latest-arm64
